    # Use a compatible base image (e.g., Node.js)
    FROM node:22 

    # Set the working directory inside the container
    WORKDIR /app

    # Copy package.json and package-lock.json to install dependencies
    COPY package*.json ./

    # Install project dependencies
    RUN npm install -g vercel

    RUN npm install

    # Copy the rest of your application code
    COPY . .

    # Run the Vercel build command
    # RUN vercel build 

    # docker build -t triptools -f dockerfile.dev .
    # docker run -e .env -v ${pwd}/vercel.json:/app/vercel.json --rm -it triptools sh